version: "3"
services:
  hh:
    image: ghcr.io/dvornicked/hh:latest
    command: poetry run python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env