[tool.poetry]
name = "hh"
version = "0.1.0"
description = ""
authors = ["dvornick <dev@dvornick.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.1.2"
python-decouple = "^3.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
