# Generated by Django 4.1.2 on 2022-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hh_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
